### ISSUE TITLE
Relative path in quickfix list

### ISSUE THREAD

**Issue by c0ffeeartc** [romainl/vim-qlist#1]
I've met another usecase where include files in this form `../foo/bar.h` aren't followed correctly. After some testing this expansion gives best results:

```
let filename = fnamemodify(line, ':p:.')
```

It gives relative paths when possible, and full path when not.

**Comment by romainl** [comment]
Your suggestion doesn't seem to have any unwanted side-effect. Thank you.

See [this commit](https://github.com/romainl/vim-ilist/commit/95b77d7dc5e71a4bfa49f94dcc30ab98c8a99d01)
